sonar.projectKey=wireops_wireops
sonar.organization=wireops


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=wireops
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Ignore githubactions:S6505 (Executing npm/Yarn scripts can be security-sensitive) 
# Nuxt and Vue ecosystem heavily rely on postinstall scripts to build stubs and prepare the framework.
# Only safe since we ensure locked versions (npm ci) and clean environments.
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S6505
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
