package pb_migrations

import (
	"database/sql"
	"errors"
	"fmt"
	"os"

	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"

	"github.com/wireops/wireops/internal/crypto"
	"github.com/wireops/wireops/internal/secrets"
)

// Migration 53: SOPS+age support (P1.5).
//
//   - repositories gets an auto-generated age keypair: sops_age_key (hidden,
//     encrypted private key) and sops_age_public_key (plain, shown in the UI so
//     operators can `sops -e --age <pubkey> secrets.yaml`). Generated by the
//     OnRecordCreate("repositories") hook in internal/hooks/pb_hooks.go, not
//     here — this migration only adds the columns.
//   - integrations gets a "locked" flag: locked integrations can't be
//     enabled/disabled from the API (see internal/routes/integrations.go).
//   - a "sops" row is seeded into integrations, always enabled and locked,
//     since SOPS activates automatically per-stack whenever a secrets.yaml
//     file is found next to wireops.yaml — there's no connection to toggle.
func init() {
	m.Register(func(app core.App) error {
		if err := addRepositorySopsFields(app); err != nil {
			return err
		}
		if err := backfillRepositorySopsKeys(app); err != nil {
			return err
		}
		if err := addIntegrationsLockedField(app); err != nil {
			return err
		}
		return seedSopsIntegration(app)
	}, func(app core.App) error {
		if err := removeSopsIntegration(app); err != nil {
			return err
		}
		if err := removeIntegrationsLockedField(app); err != nil {
			return err
		}
		return removeRepositorySopsFields(app)
	})
}

func addRepositorySopsFields(app core.App) error {
	col, err := app.FindCollectionByNameOrId("repositories")
	if err != nil {
		return err
	}

	if col.Fields.GetByName("sops_age_key") == nil {
		col.Fields.Add(&core.TextField{Name: "sops_age_key", Hidden: true})
	}
	if col.Fields.GetByName("sops_age_public_key") == nil {
		col.Fields.Add(&core.TextField{Name: "sops_age_public_key"})
	}

	return app.Save(col)
}

// backfillRepositorySopsKeys generates an age keypair for every repository
// that predates this migration and therefore never went through the
// OnRecordCreate("repositories") hook in internal/hooks/pb_hooks.go — without
// this, any pre-existing repo that already has (or later adds) a
// secrets.yaml would hard-fail every sync with "no SOPS age key configured".
func backfillRepositorySopsKeys(app core.App) error {
	repositories, err := app.FindAllRecords("repositories")
	if err != nil {
		return err
	}

	secretKey := crypto.NormalizeSecretKey(os.Getenv("SECRET_KEY"))
	for _, repo := range repositories {
		if repo.GetString("sops_age_key") != "" {
			continue
		}

		privateKey, publicKey, err := secrets.GenerateAgeKeypair()
		if err != nil {
			return fmt.Errorf("failed to generate SOPS age keypair for repository %q: %w", repo.Id, err)
		}

		encrypted, err := crypto.Encrypt([]byte(privateKey), secretKey)
		if err != nil {
			return fmt.Errorf("failed to encrypt SOPS age key for repository %q: %w", repo.Id, err)
		}

		repo.Set("sops_age_key", encrypted)
		repo.Set("sops_age_public_key", publicKey)
		if err := app.Save(repo); err != nil {
			return fmt.Errorf("failed to save SOPS age keypair for repository %q: %w", repo.Id, err)
		}
	}

	return nil
}

func removeRepositorySopsFields(app core.App) error {
	col, err := app.FindCollectionByNameOrId("repositories")
	if err != nil {
		return err
	}

	for _, name := range []string{"sops_age_key", "sops_age_public_key"} {
		if field := col.Fields.GetByName(name); field != nil {
			col.Fields.RemoveById(field.GetId())
		}
	}

	return app.Save(col)
}

func addIntegrationsLockedField(app core.App) error {
	col, err := app.FindCollectionByNameOrId("integrations")
	if err != nil {
		return err
	}

	if col.Fields.GetByName("locked") == nil {
		col.Fields.Add(&core.BoolField{Name: "locked"})
	}

	return app.Save(col)
}

func removeIntegrationsLockedField(app core.App) error {
	col, err := app.FindCollectionByNameOrId("integrations")
	if err != nil {
		return err
	}

	if field := col.Fields.GetByName("locked"); field != nil {
		col.Fields.RemoveById(field.GetId())
	}

	return app.Save(col)
}

func seedSopsIntegration(app core.App) error {
	col, err := app.FindCollectionByNameOrId("integrations")
	if err != nil {
		return err
	}

	existing, err := app.FindFirstRecordByFilter("integrations", "slug = {:slug}", map[string]any{"slug": "sops"})
	if err == nil && existing != nil {
		return nil
	}

	record := core.NewRecord(col)
	record.Set("slug", "sops")
	record.Set("enabled", true)
	record.Set("locked", true)
	record.Set("config", map[string]any{})

	return app.Save(record)
}

func removeSopsIntegration(app core.App) error {
	record, err := app.FindFirstRecordByFilter("integrations", "slug = {:slug}", map[string]any{"slug": "sops"})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}
		return err
	}
	return app.Delete(record)
}
